name: dart_github_actions
description: A project for writing Github Workflows using a type-safe api rather than yaml.
version: 0.1.0
homepage: https://github.com/scottbisaillon/dart_github_actions
repository: https://github.com/scottbisaillon/dart_github_actions

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
